# Generated by Django 6.0.6 on 2026-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_midnightsales_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.IntegerField()),
                ('delivered', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='trending',
            name='category',
            field=models.CharField(choices=[('flagship', 'Flagship'), ('gaming', 'Gaming'), ('budget', 'Budget'), ('foldable', 'Foldable'), ('iPhone', 'IPhone'), ('samsung', 'Samsung'), ('onePlus', 'OnePlus'), ('google', 'Google'), ('xiaomi', 'Xiaomi'), ('asus', 'Asus')], default='flagship', max_length=20),
        ),
    ]
